from dataclasses import dataclass

from fastapi import Request

from app.utils.device import parse_user_agent


@dataclass(frozen=True)
class ClientContext:
    ip_address: str | None
    user_agent: str | None
    browser: str
    operating_system: str
    device: str


def get_client_ip(request: Request) -> str | None:
    forwarded_for = request.headers.get("x-forwarded-for")
    if forwarded_for:
        return forwarded_for.split(",")[0].strip()
    return request.client.host if request.client else None


def get_client_context(request: Request) -> ClientContext:
    user_agent = request.headers.get("user-agent")
    device_info = parse_user_agent(user_agent)
    return ClientContext(
        ip_address=get_client_ip(request),
        user_agent=user_agent,
        browser=device_info.browser,
        operating_system=device_info.operating_system,
        device=device_info.device,
    )


def resolve_client_context(request: Request) -> ClientContext:
    """Return the ClientContext cached on request.state by AuditMiddleware,
    computing it on demand if the middleware hasn't run (e.g. direct unit
    testing of a dependency in isolation).
    """
    cached: ClientContext | None = getattr(request.state, "client_context", None)
    return cached if cached is not None else get_client_context(request)


SYSTEM_CLIENT_CONTEXT = ClientContext(
    ip_address=None, user_agent=None, browser="Unknown", operating_system="Unknown", device="Unknown"
)
"""Placeholder context for audit log entries generated by background jobs
(e.g. SessionExpiryService) that have no originating HTTP request.
"""
