from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
from starlette.requests import Request
from starlette.responses import Response

_SECURITY_HEADERS = {
    "X-Frame-Options": "DENY",
    "X-Content-Type-Options": "nosniff",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    "Permissions-Policy": "geolocation=(), microphone=(), camera=()",
    "Content-Security-Policy": "default-src 'self'; frame-ancestors 'none'",
}

# Swagger UI and ReDoc load JS/CSS from cdn.jsdelivr.net.  A blanket
# 'self'-only CSP blocks those resources and renders the docs page blank.
# We relax the policy *only* for the documentation paths.
_DOCS_PATHS = ("/docs", "/redoc", "/openapi.json")

_DOCS_CSP = (
    "default-src 'self'; "
    "script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; "
    "style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; "
    "img-src 'self' data: https://cdn.jsdelivr.net https://fastapi.tiangolo.com; "
    "font-src 'self' https://cdn.jsdelivr.net https://fonts.gstatic.com; "
    "frame-ancestors 'none'"
)


class SecurityHeadersMiddleware(BaseHTTPMiddleware):
    """Adds standard security headers to every response, including ones
    generated by other middleware (e.g. a 429 from the rate limiter) - this
    must be the outermost middleware in the stack for that to hold.
    """

    async def dispatch(self, request: Request, call_next: RequestResponseEndpoint) -> Response:
        response = await call_next(request)

        is_docs = any(request.url.path.endswith(p) for p in _DOCS_PATHS)

        for header, value in _SECURITY_HEADERS.items():
            if header == "Content-Security-Policy" and is_docs:
                response.headers.setdefault(header, _DOCS_CSP)
            else:
                response.headers.setdefault(header, value)
        return response

